spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat_life
  rabbitmq:
    password: guest
    username: guest
    publisher-returns: true
    publisher-confirm-type: correlated
    host: localhost
    port: 5672
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 5000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: scaudachuang.catlife.publisher.entity


detect:
  max-img-size: 3145728
  max-retry-times: 10
  max-task-cache: 1000
